### ISSUE TITLE
Pig dice game 규칙 리서치

### ISSUE THREAD

**Issue by ghost** [fc-2line-left-team/pig-the-dice-game#1]
## 내용

피그더다이스 게임 룰에 대해 조사하겠습니다.

## 레퍼런스
https://m.blog.naver.com/mathdonga/221430487027

**Comment by chipmunk-dev** [comment]
넹 잘부탁드립니다.

**Comment by chipmunk-dev** [comment]
assignee랑 Label 변경해둘게요!
