### ISSUE TITLE
pig-the-dice-game by baker-lee

### ISSUE THREAD

**Issue by baker-lee** [fc-2line-left-team/pig-the-dice-game#2]
## 내용

- [x]  게임의 역사

- [x] 게임의 룰 및 승리 조건

- [x] 추가적인 규칙
## 레퍼런스

https://en.wikipedia.org/wiki/Pig_(dice_game)

**Comment by chipmunk-dev** [comment]
오 이슈 내용과 담당자, 라벨을 지정해주세요~

**Comment by baker-lee** [comment]
> 

내용 입력했습니다 담당자랑 라벨은 어떻게 지정하나요...ㅠ

**Comment by chipmunk-dev** [comment]
우측 Assignees와 Labels를 클릭하면 지정할 수 있습니다!

<img width="317" alt="스크린샷 2022-09-16 오후 3 59 04" src="https://user-images.githubusercontent.com/107650362/190576261-10734fe9-14e5-4261-8af6-86855dd1806a.png">

**Comment by baker-lee** [comment]
![image](https://user-images.githubusercontent.com/113500934/190576506-e2956d83-7b0d-40d3-8765-419c6552b4cf.png)
옵션 표시가 저한테는 없는데 권한의 차이인가요??

**Comment by chipmunk-dev** [comment]
> ![image](https://user-images.githubusercontent.com/113500934/190576506-e2956d83-7b0d-40d3-8765-419c6552b4cf.png) 옵션 표시가 저한테는 없는데 권한의 차이인가요??

---

죄송함다.. 권한 드렸어요 ㅠ

**Comment by chipmunk-dev** [comment]
해당 이슈 작업 완료되었으면 close해주셔도 됩니당
